spring.application.name=lms

spring.datasource.url=jdbc:mysql://localhost:3306/lms_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema=always

server.port = 8080
app.jwt.secret = "VGhpcy1pcy1hLXNlY3VyZS0yNTYtYml0LWtleS1leGFtcGxl"

# This tells jpa that to batch fetch 20 items at once.
# we add this because for a course, it does not join sections and lessons both
# because of the cartesian product problem.
spring.jpa.properties.hibernate.default_batch_fetch_size=20
